server:
  port: 8090
  servlet:
    context-path: /wy
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wy1?useSSL=false&characterEncoding=utf-8&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wy.model

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.wanghuan: DEBUG